$env:POSTGRES_URL="postgresql://postgres.llfnkdxldxxhyqfherno:FLUIDEZ2025j@aws-1-us-east-2.pooler.supabase.com:6543/postgres?pgbouncer=true"
$env:DATABASE_URL="postgresql://postgres.llfnkdxldxxhyqfherno:FLUIDEZ2025j@aws-1-us-east-2.pooler.supabase.com:6543/postgres?pgbouncer=true"

# Supabase config for client
$env:NEXT_PUBLIC_SUPABASE_URL="https://llfnkdxldxxhyqfherno.supabase.co"
$env:NEXT_PUBLIC_SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxsZm5rZHhsZHh4aHlxZmhlcm5vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk3OTMzMDMsImV4cCI6MjA3NTM2OTMwM30._xn9Q-neL5o4-zsnGx-jFuU_ey51CEXOBNDZiSliJ90"

# Supabase config for server
$env:SUPABASE_URL="https://llfnkdxldxxhyqfherno.supabase.co"
$env:SUPABASE_SERVICE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxsZm5rZHhsZHh4aHlxZmhlcm5vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1OTc5MzMwMywiZXhwIjoyMDc1MzY5MzAzfQ.xqd_5jHs9MB8yq5xhkkcRTK-qF7TLmT7_rYSb0DQJAk"
$env:SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxsZm5rZHhsZHh4aHlxZmhlcm5vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk3OTMzMDMsImV4cCI6MjA3NTM2OTMwM30._xn9Q-neL5o4-zsnGx-jFuU_ey51CEXOBNDZiSliJ90"

$env:NODE_ENV="production"

npm start
